name: CI/CD Pipeline for Node.js

#Trigger point: When ever changes merges to main branch
on:
  push:
    branches:
      - main

# Install the Node.js dependencies
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

#Build the image and push to Docker Hub
  buildAndPush:
    runs-on: ubuntu-latest
    needs: buildAndTest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

# Deploy the Image in Kubernetes (EKS, GKE)
  deploy:
    runs-on: ubuntu-latest
    needs: buildAndPush
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

        
        # Store the kube config in github Secrets
      - name: Set Up Kubectl
        run: |
            echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config

        # If deployment not successful It will revert the deployment
      - name: Deploy to Kubernetes
        run: |
            kubectl apply -f CICDDeployment/deployment.yaml
            kubectl rollout status deployment/node-app || kubectl rollout undo deployment/node-app